version: "3"
services:
  synapse:
    image: matrixdotorg/synapse:latest
    network_mode: host
    environment:
      SYNAPSE_SERVER_NAME: localhost
      SYNAPSE_REPORT_STATS: 'no'
      UID: 1000
      GID: 1000
    volumes:
      - './synapse-data:/data'
  inspircd:
    image: inspircd/inspircd-docker:latest
    network_mode: host
