version: "3"
services:
  synapse:
    image: matrixdotorg/synapse:latest
    network_mode: host
    environment:
      SYNAPSE_SERVER_NAME: localhost
      SYNAPSE_REPORT_STATS: 'no'
      UID: 1000
      GID: 1000
    volumes:
      - ./docker-compose/init/synapse-init.sh:/synapse-init.sh:ro
      - './synapse-data:/data'
    entrypoint: /synapse-init.sh
  inspircd:
    image: inspircd/inspircd-docker:latest
    network_mode: host
    environment:
      # use: "/oper oper oper" to gain opers
      INSP_OPER_HASH: 'sha256'
      INSP_OPER_PASSWORD_HASH: 'fcbe80d4d1bcc6f21964c75ea2e5d26cdd67642ed7187d6bde8aae180a093576'
      INSP_OPER_SSLONLY: 'no'
